In [1]:
import torch
print(torch.__version__)

2.14.0+cu126


In [2]:
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.14.0+cu126
CUDA available: True
CUDA version: 12.6
GPU: NVIDIA GeForce GTX 1650


For neural network

In [3]:
import torch.nn as nn

In [76]:
from torch.utils.data import Dataset,DataLoader

In [15]:
x= torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [12]:
x= torch.tensor(1)
print(x)

tensor(1)


In [16]:
print(x.shape)

torch.Size([3])


In [17]:
x = torch.tensor([10,20,30])
print(x.shape)

In [38]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x)
print(x.shape)
print(x.size())
print(x.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([2, 3])
2


In [22]:
x = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(x.shape)

torch.Size([2, 2, 2])


In [23]:
x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

print(x.dtype)

torch.float32


In [26]:
x = torch.zeros(2, 3)

print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
x = torch.ones(2, 3)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x = torch.rand(2, 3)

print(x)

tensor([[0.0759, 0.7306, 0.7838],
        [0.3189, 0.7125, 0.7007]])


In [30]:
x = torch.arange(0, 10)

print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
x = torch.arange(0, 10,2)

print(x)

tensor([0, 2, 4, 6, 8])


In [37]:
print(x.ndim)

1


In [39]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

In [40]:
print(x[0])

tensor([10, 20, 30])


In [41]:
print(x[0,0])

tensor(10)


In [42]:
print(x[:, 2])

tensor([30, 60])


In [43]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print(x[:, 0])

tensor([10, 40])


In [44]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)

tensor([5, 7, 9])


In [45]:
print(b - a)

tensor([3, 3, 3])


In [46]:
print(a * b)

tensor([ 4, 10, 18])


In [47]:
print(b / a)

tensor([4.0000, 2.5000, 2.0000])


In [48]:
x = torch.tensor([2, 3, 4])

print(x ** 2)

tensor([ 4,  9, 16])


In [49]:
x = torch.tensor([1, 2, 3, 4])

print(torch.sum(x))

tensor(10)


In [50]:
x = torch.tensor([1, 2, 3, 4])

print(torch.sum(x))

tensor(10)


In [51]:
print(torch.max(x))
print(torch.min(x))

tensor(4)
tensor(1)


In [53]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

y = x.flatten()

print(y)

tensor([1, 2, 3, 4])


In [54]:
x = torch.tensor([1, 2, 3])

print(x.shape)

y = x.unsqueeze(0)

print(y.shape)

torch.Size([3])
torch.Size([1, 3])


In [62]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

C = torch.matmul(A, B)
C = A @ B

print(C)

tensor([[19, 22],
        [43, 50]])


In [63]:
import numpy as np

array = np.array([1, 2, 3])

tensor = torch.from_numpy(array)

print(tensor)

tensor([1, 2, 3])


In [64]:
array = tensor.numpy()

print(array)

[1 2 3]


In [71]:
x = torch.tensor(
    2.0,
    requires_grad=True
)

y = x ** 2

y.backward()

print(x.grad)

tensor(4.)


In [104]:
class StudentDataset(Dataset):

    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]

In [105]:
X = torch.tensor([
    [2.0, 60.0],
    [4.0, 70.0],
    [6.0, 80.0],
    [8.0, 90.0]
])

y = torch.tensor([
    0,
    0,
    1,
    1
])

In [106]:
dataset = StudentDataset(X, y)

print(len(dataset))

4


In [107]:
print(dataset[0])

(tensor([ 2., 60.]), tensor(0))


In [108]:
from torch.utils.data import DataLoader

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

In [109]:
for X_batch, y_batch in loader:
    print("xbatch:",X_batch)
    print(y_batch)

xbatch: tensor([[ 8., 90.],
        [ 2., 60.]])
tensor([1, 0])
xbatch: tensor([[ 6., 80.],
        [ 4., 70.]])
tensor([1, 0])


In [110]:
import torch.nn as nn

In [111]:
class SimpleModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer = nn.Linear(2, 1)

    def forward(self, x):
        return self.layer(x)

In [117]:
model = SimpleModel()

print(model)

SimpleModel(
  (layer): Linear(in_features=2, out_features=1, bias=True)
)


In [113]:
print("Weights:")
print(model.layer.weight)

print("Bias:")
print(model.layer.bias)

Weights:
Parameter containing:
tensor([[0.6484, 0.3434]], requires_grad=True)
Bias:
Parameter containing:
tensor([0.2183], requires_grad=True)


In [114]:
nn.Linear(2, 1)

Linear(in_features=2, out_features=1, bias=True)

In [118]:
class SimpleNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(2, 8)
        self.layer2 = nn.Linear(8, 1)

    def forward(self, x):

        x = self.layer1(x)
        x = self.layer2(x)

        return x

In [120]:
relu = nn.ReLU()

x = torch.tensor([
    [-2.0, -1.0, 0.0, 2.0, 3.0]
])

print(relu(x))

tensor([[0., 0., 0., 2., 3.]])


In [122]:
sigmoid = nn.Sigmoid()

x = torch.tensor([
    [-2.0, 0.0, 2.0]
])

print(sigmoid(x))

tensor([[0.1192, 0.5000, 0.8808]])


In [123]:
softmax = nn.Softmax(dim=1)

x = torch.tensor([
    [2.0, 1.0, 0.5]
])

print(softmax(x))

tensor([[0.6285, 0.2312, 0.1402]])


In [125]:
class SimpleNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(2, 8)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(8, 1)

    def forward(self, x):

        x = self.layer1(x)

        x = self.relu(x)

        x = self.layer2(x)

        return x

In [126]:
loss_fn = nn.MSELoss()

In [127]:
actual = torch.tensor([
    [10.0]
])

prediction = torch.tensor([
    [8.0]
])

loss = loss_fn(
    prediction,
    actual
)

print(loss)

tensor(4.)


In [128]:
actual = torch.tensor([
    [10.0]
])

prediction = torch.tensor([
    [8.0]
])

loss = loss_fn(
    prediction,
    actual
)

print(loss)

tensor(4.)


In [129]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

In [130]:
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [131]:
for epoch in range(10):

    # Forward
    prediction = model(X)

    # Loss
    loss = loss_fn(
        prediction,
        y
    )

    # Clear old gradients
    optimizer.zero_grad()

    # Calculate gradients
    loss.backward()

    # Update weights
    optimizer.step()

    print(
        "Epoch:",
        epoch,
        "Loss:",
        loss.item()
    )

c:\Users\HEMIL\Desktop\AIMLInternTask\.venv\Lib\site-packages\torch\nn\modules\loss.py:630: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch: 0 Loss: 118.11285400390625
Epoch: 1 Loss: 116.33692932128906
Epoch: 2 Loss: 114.57486724853516
Epoch: 3 Loss: 112.8268814086914
Epoch: 4 Loss: 111.09321594238281
Epoch: 5 Loss: 109.37405395507812
Epoch: 6 Loss: 107.66961669921875
Epoch: 7 Loss: 105.98013305664062
Epoch: 8 Loss: 104.30577087402344
Epoch: 9 Loss: 102.64673614501953


In [133]:
import torch

X = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

y = torch.tensor([
    [3.0],
    [5.0],
    [7.0],
    [9.0],
    [11.0]
])

In [134]:
import torch.nn as nn

model = nn.Linear(
    1,
    1
)

In [135]:
loss_fn = nn.MSELoss()

In [136]:
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

In [137]:
for epoch in range(1000):

    prediction = model(X)

    loss = loss_fn(
        prediction,
        y
    )

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 100 == 0:
        print(
            "Epoch:",
            epoch,
            "Loss:",
            loss.item()
        )

Epoch: 0 Loss: 105.15606689453125
Epoch: 100 Loss: 0.016828525811433792
Epoch: 200 Loss: 0.008548294194042683
Epoch: 300 Loss: 0.004342279862612486
Epoch: 400 Loss: 0.00220571574755013
Epoch: 500 Loss: 0.0011204233160242438
Epoch: 600 Loss: 0.0005691383266821504
Epoch: 700 Loss: 0.0002891075855586678
Epoch: 800 Loss: 0.00014685787027701735
Epoch: 900 Loss: 7.459828339051455e-05


In [138]:
for epoch in range(1000):

    prediction = model(X)

    loss = loss_fn(
        prediction,
        y
    )

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 100 == 0:
        print(
            "Epoch:",
            epoch,
            "Loss:",
            loss.item()
        )

Epoch: 0 Loss: 3.7893434637226164e-05
Epoch: 100 Loss: 1.924816933751572e-05
Epoch: 200 Loss: 9.777420928003266e-06
Epoch: 300 Loss: 4.9666568884276785e-06
Epoch: 400 Loss: 2.523409193599946e-06
Epoch: 500 Loss: 1.2818849199902616e-06
Epoch: 600 Loss: 6.512733534691506e-07
Epoch: 700 Loss: 3.3102483598668186e-07
Epoch: 800 Loss: 1.68304907788297e-07
Epoch: 900 Loss: 8.550241403781911e-08


Load Model

In [139]:
model = nn.Linear(
    1,
    1
)

In [141]:
from pathlib import Path

model_path = Path.cwd() / "model.pth"

if not model_path.exists():
    torch.save(model.state_dict(), model_path)
    print(f"Model saved to: {model_path}")

model.load_state_dict(
    torch.load(model_path, map_location="cpu")
)

model.eval()
print("Model loaded successfully.")

Model saved to: c:\Users\HEMIL\Desktop\AIMLInternTask\PytorchBasics\model.pth
Model loaded successfully.


In [142]:
model.eval()

Linear(in_features=1, out_features=1, bias=True)