Singal neuron 
Perceptron

In [1]:
import torch
import torch.nn as nn

In [2]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

In [10]:
print(neuron.weight)
print(neuron.bias)


Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)
Parameter containing:
tensor([0.5304], requires_grad=True)


In [4]:
output = neuron(inputs)

In [5]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [6]:
# verify ... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [7]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [126]:
import torch
import torch.nn as nn

In [127]:
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

In [128]:
print(model[0].weight)
print(model[0].bias)

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153]], requires_grad=True)
Parameter containing:
tensor([ 0.6233, -0.5188,  0.6146,  0.1323], requires_grad=True)


In [129]:
torch.manual_seed(42)
x = torch.tensor([
    [2.0, 3.0]
])

In [130]:
output = model(x)
print(output)

tensor([[1.8679]], grad_fn=<AddmmBackward0>)
