In [2]:
import numpy as np
import time

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr,type(arr))

Why numpy is fast?

In [ ]:
size = 100_00_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
np_array = np.array(py_list)
end = time.time()
print("Time taken to create python array:", end - start)


np_array = np.array(py_list)
start = time.time()
sq_array = np.square(np_array)
end = time.time()
print("Time taken to create NumPy array:", end - start)


In [ ]:
import sys
print("Size of python list:", sys.getsizeof(py_list)*len(py_list),"bytes")
print("Size of NumPy array:", np_array.nbytes,"bytes")


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr,arr.dtype,arr.shape)

arr = np.array([1, 2, 3, 4, 5,"hello"])
print("Array:", arr,type(arr))

In [ ]:
arr = np.array([[1,2,3,],[4,5,6]])
print(arr,arr.shape)

In [ ]:
arr1= np.zeros((2,3),dtype="int64") #type casting
print(arr1,arr1.shape,type(arr1),arr1.dtype)

arr1= np.ones((2,3),dtype="int64")
print(arr1,arr1.shape,type(arr1),arr1.dtype)

arr1= np.full((2,3),100)
print(arr1,arr1.shape,type(arr1),arr1.dtype)

arr1= np.eye(3)
print(arr1,arr1.shape,type(arr1),arr1.dtype)

arr1 = np.arange(0,11)
print(arr1,arr1.shape)

arr1 = np.arange(0,11,2)
print(arr1,arr1.shape)

arr1 = np.linspace(1,100,4)
print(arr1,arr1.shape)

In [53]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9,]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


reshape

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshape = arr.reshape((3,2))
print(reshape,reshape.shape)

flattened = reshape.flatten() #converts 2D => 1D
print(flattened, flattened.shape)

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr[0])

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 
print(arr[0][1]) #2
print(arr[1][2]) #6

#Fancy indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx])

#Boolean indexing
print(arr[arr > 2]) #nums greater than 2
print(arr[arr % 2 == 0]) #even nums

In [ ]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) #[3, 4, 5, 6]
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]
print(arr[::-1]) #[7 6 5 4 3 2 1]

In [ ]:
# Copy vs View by Slicing
#Sliced list is a copy
# py_list = [1, 2, 3, 4, 5]
# copy_list = py_list[1:4] #[2, 3, 4]
# copy_list[1] = 333

# print(copy_list)
# print(py_list)



#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy() #[2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

Numpy Data types:
int,floating,boolean,complex,string,object

In [ ]:
arr = np.array([1,2,3.14,4,5])
print(arr,arr.dtype)

arr1 =np.array([3 + 5j])
print(arr1,arr1.dtype)

arr2 =np.array([2 + 3j])
print(arr2,arr2.dtype)

print(arr1+arr2)

arr = np.array(["prime",{1,2,3},3.14])
print(arr,arr.dtype)


In [5]:
# Operations along Axes
arr2D = np.array([[1, 2, 3,14], [4, 5, 6,16], [7, 8, 9,19]])

print(arr2D)
print(np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3]) #row(0, 1, 2) & col(1, 2)

[[ 1  2  3 14]
 [ 4  5  6 16]
 [ 7  8  9 19]]
94
[12 15 18 49]
[20 31 43]
[[2 3]
 [5 6]
 [8 9]]


In [6]:
# 3D array
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])

print(arr3D)
print(arr3D.shape)

#Indexing
print(arr3D[0][1][1])   #4
print(arr3D[1][2][1])   #12

print(arr3D[:, :, 0])        #first col from both layers
print(arr3D[:, 0, :])        #first row from both layers

#Manipulating data
arr3D[:, 0, :] = 99          #change first row to store 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [9]:
# Vectorization & Broadcasting

#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [12]:
# Vector Normalization
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)

sum = np.sum(arr, axis = 0)
print(sum)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[ 9 12]


In [ ]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0 return index of min value
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4 return index of max value
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0 variance

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [14]:
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [15]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [21]:
print(np.round(2.678))    # 3.0 goes to nearest number
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0 always goes UP to the next integer
print(np.trunc(2.678))    # 2.0

3.0
2.0
3.0
2.0


In [18]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
